// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVdiC6U7LS49qGo1cbZdIpOyOMpNhMmAk',
    appId: '1:781733947264:web:46f6a68aad2345b8f5c365',
    messagingSenderId: '781733947264',
    projectId: 'journal-app-900b8',
    authDomain: 'journal-app-900b8.firebaseapp.com',
    storageBucket: 'journal-app-900b8.firebasestorage.app',
    measurementId: 'G-6RQSJ9H9ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kq6pAExMkfxSd7KA9Wtkn_AWmLNvTdQ',
    appId: '1:781733947264:android:ea9de8be0352c82af5c365',
    messagingSenderId: '781733947264',
    projectId: 'journal-app-900b8',
    storageBucket: 'journal-app-900b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJA3kEoc7TYubCnhICYj_KKiBQVh8Z6k',
    appId: '1:781733947264:ios:b576daa67ea1a3c4f5c365',
    messagingSenderId: '781733947264',
    projectId: 'journal-app-900b8',
    storageBucket: 'journal-app-900b8.firebasestorage.app',
    iosBundleId: 'com.example.journalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJA3kEoc7TYubCnhICYj_KKiBQVh8Z6k',
    appId: '1:781733947264:ios:b576daa67ea1a3c4f5c365',
    messagingSenderId: '781733947264',
    projectId: 'journal-app-900b8',
    storageBucket: 'journal-app-900b8.firebasestorage.app',
    iosBundleId: 'com.example.journalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVdiC6U7LS49qGo1cbZdIpOyOMpNhMmAk',
    appId: '1:781733947264:web:ca09881e395ec0bbf5c365',
    messagingSenderId: '781733947264',
    projectId: 'journal-app-900b8',
    authDomain: 'journal-app-900b8.firebaseapp.com',
    storageBucket: 'journal-app-900b8.firebasestorage.app',
    measurementId: 'G-5P1KDD8DQ5',
  );
}
